# # Use official Python image
# FROM python:3.9
#
# # Set working directory
# WORKDIR /app
#
# # Copy files
# COPY . .
#
# # Install dependencies
# RUN pip install -r requirements.txt
#
# # Expose Streamlit port
# EXPOSE 8501
#
# # Run Streamlit app
# CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
