# # Use official Python image
# FROM python:3.9
#
# # Set working directory
# WORKDIR /app
#
# # Copy files
# COPY . .
#
# # Install dependencies
# RUN pip install -r requirement.txt
#
# # Expose Flask port
# EXPOSE 5000
#
# # Run Flask server
# CMD ["python", "app.py"]
